### PR TITLE
Add tests and documentation.

### LINKED ISSUE #3: add more desi.json documentation
Motivated by #2, add more documentation about how to add a new entry to `etc/desi.json`, e.g.

1. naming constraints on the tar files, and whether those are best-practices guidelines or actually required for desiBackup and restore to work properly.
2. worked examples for using regex groups to map N>>1 directories into N>>1 tar files, and how much one should worry about the resulting size of the tar file (and how to tell).
3. worked examples for how to map the files in a directory into a tarball without accidentally mapping files in subdirectories.

Since json files don't allow comments, the existing `etc/desi.json` is only partially useful for deriving these patterns.

### LINKED ISSUE #4: add etc/desi.json validation tools
Add tools for validating the backup specifications in `etc/desi.json`, in particular:

1. do any regexes not match any files?
2. are any files in the directory tree not covered by a regex and not in the exclude list?
3. are any files covered by more than one regex?
4. would any tar specification result in a tarball > 1TB?
5. a `--manifest` option (or some equivalent name) that would generate a manifest of what files would go into what tarballs.  e.g. perhaps this would point to a directory and it would create fake *.tar files in the same hierarchy and naming that would end up on HPSS, but the contents of those files would be the listing of file paths rather than the contents of the files themselves (like `tar -tf blat.tar` would report).  This would allow someone to do a dry run and check if the results are intended before actually trying to send TB of data to HPSS.

Note that this validation would need to be run at NERSC since it needs access to the actual files; this isn't just the json syntax check of the travis test.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Fixes desihub/desiBackup#3
  - All items explicitly requested are tested for.  The existing manifest file has been extended to include not only the files backed up, but the total size as well (of the files, which will be close to, but not exactly equal t the size of a tar file).
* Fixes desihub/desiBackup#4
  - Regular expressions and idioms are documented.
  - Additional examples.

Note that the documentation part isn't actually done yet.  I just needed a PR number to refer to.

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, could you take a look at this, in particular the new documentation, the files configuration.rst and using.rst?

**Comment by weaverba137** [comment]
PS, I'm still working on some unit tests, but the documentation should be ready to go.

**Comment by weaverba137** [comment]
I'm satisfied with the current state of the unit tests, so this can be merged after the documentation is reviewed.

**Comment by sbailey** [comment]
Thank you.  This is good, especially the configuration documentation and the explained idioms.  Go ahead and merge when ready.

**Pull request merged**
